### ISSUE TITLE
Hyperv BSODs when OVS extension is enabled on a vSwitch backed by a NicTeam adapter 

### ISSUE THREAD

**Issue by mantri** [openvswitch/ovs-issues#78] opened 2015-04-03 20:31 UTC
![screen shot 2015-04-03 at 1 23 33 pm](https://cloud.githubusercontent.com/assets/1046032/6988327/0e141e86-da05-11e4-85f2-d0f08cc3d9b5.png)
1. Created a Net-AdapterTeam with two physical Nics
2. Created a new VMSwitch using this nic team.
3. Enabled OVS Extension on the VMSwitch
4. Started ovsdb-server.exe and ovs-vswitchd.exe
5. The conf.db was already present from my previous experiment so I did del-br br-pif and br-int
6. After some time the host BSOD'ed with the error shown in the attached screenshot.

**Comment by svinturis** [comment] 2015-04-06 09:07
For any reported BSOD a good starting point would be a stack trace to see more details about the modules involved in the crash. But judging from the picture you attached the BSOD is triggered by MsLbfoProvider.sys, which is a Microsoft driver. A quick search on Google [shows](https://social.technet.microsoft.com/Forums/lync/en-US/772562bc-4913-4d62-b304-3364706a0c5f/hyperv-host-node-bughceck-on-mslbfoprovidersys) that the reported BSOD is a very common issue for this module, caused by a wrong update, and a rollback to a previous version is recommended. Hope this helps.

**Comment by mantri** [comment] 2015-04-06 20:21
The Hyper-V host has auto-updates disabled and the host has not been updated for very long. This issue was known to happen if VMQ is enabled on the network adapters. However, I ensured that the VMQ is disabled.  Could not disabling LSO on the adapters cause this? My understanding was that the documentation recommends disabling LSO for performance reasons only. Does it also affect functionality?

**Comment by EitanEliahu** [comment] 2015-04-06 20:55
A stack trace or a core dump file would be appreciated.

**Comment by mantri** [comment] 2015-04-07 00:22
Apparently, github doesn't support attaching files other than images. I also tried ZenHub extension to github but could not get it to work. So I uploaded the core files here. Sorry for the inconvenience.

http://www.filedropper.com/040315-18234-01
http://www.filedropper.com/040515-16734-01

**Comment by svinturis** [comment] 2015-04-07 19:10
I have analyzed the two dumps and I cannot see the OVS driver on the stack. This might be due to the missing symbols of the OVS driver.

@mantri: Will you be willing to test the crashing scenario using a custom driver?

**Comment by mantri** [comment] 2015-04-07 19:20
@svinturis: I can test with custom driver but it might take a little while.  I currently am held up with some other things and don't have a host ready.

**Comment by mantri** [comment] 2015-07-10 17:37
@svinturis , @nithinrajub : Is anyone looking into this? I see no one assigned to this issue. Thanks!

**Comment by aserdean** [comment] 2015-12-10 17:39
@mantri could you try with release 2.4 to see if you are still encountering problems

**Comment by aserdean** [comment] 2016-02-11 03:40
Closing this issue since it has been a long time it was updated. If the issue reproduces on the updated code-base a new issue can be opened.

**Closed as completed by aserdean** 2016-02-11 03:40 UTC

**Comment by mantri** [comment] 2016-03-22 23:41
@aserdean : I just tried this with the latest installer from cloudbase at https://www.cloudbase.it/downloads/openvswitch-hyperv-installer-beta.msi 
and still see this issue. 

Here is the powershell transcript to show my setup:

[ovs_setup_log.txt](https://github.com/openvswitch/ovs-issues/files/185171/ovs_setup_log.txt)

The BSOD is still the same (due to MsLbfoProvider.sys). Please let me know what I am missing. In all the examples shown in the CloudBase blogs the VMSwitch is attached to a stand-alone NIC. Could you please try/post one with a NIC team to see if this works as expected? Thanks!

Screenshot of BSOD:

<img width="990" alt="screen shot 2016-03-22 at 3 44 04 pm" src="https://cloud.githubusercontent.com/assets/1046032/13971361/eabdeba6-f04c-11e5-892c-278209d25f3d.png">

**Comment by aserdean** [comment] 2016-03-23 00:57
Please move this question to our Q/A http://ask.cloudbase.it/questions/ and we could continue this discussion further about our installer.

As an idea about OVS, port names have changed and we are currently implementing multiple internal/external ports support (aka multiple NIC support, bonding etc will be part of that feature).

This is a scenario that we do not test in general. I have recently deployed a scenario with NetLbfo, in which OVS was pinned to a NetLbfoTeamNic member, and it worked. I will try your environment tomorrow to see what is going on.

Just a warning I could not get it too work until I had my environment updated with the latest MSFT patches.
