### ISSUE TITLE
ovs-dpctl.exe does not refresh state from the database schema

### ISSUE THREAD

**Issue by mantri** [openvswitch/ovs-issues#73] opened 2015-04-01 22:26 UTC
Adding any port/bridge via ovs-vsctl.exe needs vswitchd and ovsdb-server to restart to pick up new changes.

**Comment by nithinrajub** [comment] 2015-04-14 17:49
duplicate of https://github.com/openvswitch/ovs-issues/issues/72.

**Closed as completed by nithinrajub** 2015-04-14 17:49 UTC
