### ISSUE TITLE
The Hyper-V Manager UI can not be used while the extension is enabled

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#10] opened 2014-08-04 20:11 UTC
This issue happens when trying to connect Hyper-V Manager UI to a VM using the 
same interface connected to the Hyper-V virtual switch used by the OVS extension.

Steps to reproduce the issue:

Create a virtual switch, enable the OVS forwarding extension for that specific 
switch and try to connect with Hyper-V Manager to it.

The problems itself can be found in the function OvsStartNBLIngress and the part of the
code impacting the functionality is the following:
        if (curNb->Next != NULL) {
            /\* XXX: This case is not handled yet. */
            ASSERT(FALSE);
        } else {

For the sake of testing I commented that part out and was able to connect to the
Hyper-V management service which enabled me to connect to the VM themselves 
and set up the VXLAN tunnel.

**Comment by ssp0** [comment] 2014-08-04 21:23
Right, so this is related to https://github.com/openvswitch/ovs-issues/issues/2. Once we fix that, this will work too.

**Comment by nithinrajub** [comment] 2014-08-05 01:57
As it has been discussed, this is not a super-simple case to handle esp. the such a packet comes from a VIF, and it subject to tunneling etc.

There's an API in OvsBufferMgmt.c that was written to handle this case: OvsFullCopyToMultipleNbls(). Usage of this API can be explored.

At a minimum, we should get do the following patch:
if (curNb->Next != NULL) {
    /\* XXX: This case is not handled yet. */
-    ASSERT(FALSE);
-   goto dropit;
  }

This should take care of the hang/uninstall issue caused by leaking NBLs.

**Comment by nithinrajub** [comment] 2014-08-05 15:42
Alin,
Can you pls. take care of adding the workaround I suggested? As I mentioned, the workaround is straight forward - to drop the NBL by caling goto dropit, instead of ASSERT(FALSE). I can take care of it later this week, otherwise.

thanks!

**Comment by aserdean** [comment] 2014-08-05 15:46
Sure Nithin I will give it a go.

**Comment by nithinrajub** [comment] 2014-08-05 17:45
Alin, I'm assigning this to you for tracking purposes. Pls. feel free to bounce it back to us if you think that is more appropriate.

We'll use this issue for putting in the workaround, and the other issue to put in a proper fix.

**Comment by aserdean** [comment] 2014-08-06 06:09
Nithin, I tried out what you suggested, but the problem is not just the leaking NBLs it is also that packets are not sent to ports either.

The easiest way for a quick workaround, until the proper patch is written, is too have the following:
if (curNb->Next != NULL) {
/\* XXX: This case is not handled yet. */
ASSERT(FALSE);
} 
In other words just drop the else. This way I can connect to the Hyperv Manager UI.

I can drop a patch on the ML for this until we have the proper version.

**Comment by nithinrajub** [comment] 2014-08-06 06:16
Alin,
Thanks for trying this out. Yes, the workaround I suggested would drop the NBLs on the floor, and not forward them to any of the ports. The use of this is that your uninstall script or the HyperV Manager UI would not hang indefinitely anymore.

I don't completely understand the workaround you are suggesting. The code you posted in your code looks exactly like the code we have. When you say, "just drop the else", what do you mean? This is the patch I had in mind:
http://paste.openstack.org/show/90901/

If you drop the else part altogether, regular NBLs (ie with single NB) won't get processed at all.

**Comment by aserdean** [comment] 2014-08-06 06:57
This is what I have in mind for the moment:
http://pastebin.com/b2Jite9t

Not the whole else statement block just the else :). 
For the time being from my point of view it will be suffice.

**Comment by nithinrajub** [comment] 2014-08-06 17:47
Alin,
This is what I can read from your patch:
- We don't need to drop NBLs with multiple NBs. We can process them normally. ie. Call the sequence of Flow lookup, Actions execute etc.
- However, we'll just ASSERT for the time being to catch such a case on debug builds, but on release builds, we'll continue regular processing.

We in the VMware team recognize that each NB is essentially a complete L2 packet. It shares some common traits with the other NBs in the same NBL, Eg. same source port. But, in itself each NB is a fu;l L2 packet. We'll have to run Flow lookup, and actions execute on each of the NBs - either by putting them into one NBL each or otherwise. This is the longer term fix. I change you are suggesting seems to assume that the rest of the code can handle multiple NBs, but I am not sure if it can. We have not tested it also. For Eg. what if such an NBL is received from a VIF and such an NBL needs to be encapsulated? ie. each NB has to be encapsulated.

Hence I suggested the workaround where we just drop the NBL and avoid kernel crash (due to ASSERT) and hangs during uninstall. I can work on this workaround, if you want to investigate what the longer term fix is. Is that reasonable?

**Comment by aserdean** [comment] 2014-08-06 18:16
Nithin,

>    We don't need to drop NBLs with multiple NBs. We can process them normally. ie. Call the sequence of Flow lookup, Actions execute etc.
>    However, we'll just ASSERT for the time being to catch such a case on debug builds, but on release builds, we'll continue regular processing.

That is correct.

I agree with you that this is not a long term fix, and in the future we will investigate if every NB should be put into one NBL or otherwise.

Your suggestion is also valid in the case of the kernel crash and uninstall however it does not allow connection to Hyperv Manager UI.

What I proposed above seems to work under Release for uninstall, avoid crash and connect with the Hyperv Manager UI.

My setup is:
2 Hyper-Vs
VXLAN tunnel between them
1 Windows VM on top of each Hyper-v.

**Comment by nithinrajub** [comment] 2014-08-13 18:18
Same as https://github.com/openvswitch/ovs-issues/issues/2

**Closed as completed by nithinrajub** 2014-08-13 18:18 UTC
Labels: bug
