### ISSUE TITLE
[Hyperv-Ovs]:Disabling switch extensions for Openvswitch takes infinite time.

### ISSUE THREAD

**Issue by Thalabathy** [openvswitch/ovs-issues#108] opened 2016-02-11 03:27 UTC
Observed disabling switch extensions for openvswitch takes longer time.
 also no options to close the window and killing task and restart is the option.

OS:windows 2012 R2 data center with GUI (all patch sets updated)
 Hardware: HP SL230 Gen8
 DATA Nic: HP FlexFabric 10Gb 2-port 554FLR-SFP+ Adapter
 Emulex Driver:10.2.531

Steps to reproduce:
 follow the steps defined under the below link.

```
 References://cloudbase.it/open-vswitch-24-on-hyperv-part-1
```
1. Ensure enabling extensions done and try to disable by un-checking the check box provided.

Observation:
  Its takes infinite to come out, meaning not at all disabling extensions happening.

Expectation:
 Its should happen with in stipulated time interval.

**Comment by aserdean** [comment] 2016-02-11 03:33
This sounds like the OVS services/daemons are running when you are trying to disable the extension.

Can you please stop all OVS binaries before trying to disable the extension and see if your issue is reproduced?

**Comment by Thalabathy** [comment] 2016-02-11 04:42
Tried after stopping OVs-DB service and I could disable the extension.

**Comment by Thalabathy** [comment] 2016-02-11 04:45
Let me try other use cases, now I have seen while (ovs-db service) running also disabling things are worked.

**Comment by aserdean** [comment] 2016-02-11 04:46
ovs-vswitchd / ovs-dpctl should be the ones that generate a hang. ovs-vswitchd has a dependency of ovsdb-server so if that previous is close the latter is also closed

**Comment by aserdean** [comment] 2016-02-14 22:21
Closing since it is a duplicate of https://github.com/openvswitch/ovs-issues/issues/27

**Closed as completed by aserdean** 2016-02-14 22:21 UTC
